services:
  - type: web
    name: ayursutra-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://lalapilane1_db_user:MHaETBmEfKad6Kcl@cluster0.q0cmctd.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        value: ayursutra_dev_secret_key_2024
      - key: PORT
        value: 5000
